"""
Whether or not to use 24-hour time.

Set to True to use 24-hour time.
Set to False to use 12-hour time.
"""
hr24 = False

"""
Timezone aliases to replace when parsing.

Aliases should appear in all lowercase and be mapped to the Region/Zone name.
"""
aliases = {
    "international date line west": "Etc/GMT+12",
    "midway island": "Pacific/Midway",
    "american samoa": "Pacific/Pago_Pago",
    "hawaii": "Pacific/Honolulu",
    "alaska": "America/Juneau",
    "pacific time": "America/Los_Angeles",
    "pacific": "America/Los_Angeles",
    "tijuana": "America/Tijuana",
    "mountain time": "America/Denver",
    "mountain": "America/Denver",
    "arizona": "America/Phoenix",
    "chihuahua": "America/Chihuahua",
    "mazatlan": "America/Mazatlan",
    "central time": "America/Chicago",
    "central": "America/Chicago",
    "saskatchewan": "America/Regina",
    "guadalajara": "America/Mexico_City",
    "mexico city": "America/Mexico_City",
    "monterrey": "America/Monterrey",
    "central america": "America/Guatemala",
    "eastern time": "America/New_York",
    "eastern": "America/New_York",
    "indianapolis": "America/Indiana/Indianapolis",
    "bogota": "America/Bogota",
    "lima": "America/Lima",
    "quito": "America/Lima",
    "atlantic time (canada)": "America/Halifax",
    "caracas": "America/Caracas",
    "la paz": "America/La_Paz",
    "santiago": "America/Santiago",
    "newfoundland": "America/St_Johns",
    "brasilia": "America/Sao_Paulo",
    "buenos aires": "America/Argentina/Buenos_Aires",
    "montevideo": "America/Montevideo",
    "georgetown": "America/Guyana",
    "puerto rico": "America/Puerto_Rico",
    "greenland": "America/Godthab",
    "mid-atlantic": "Atlantic/South_Georgia",
    "azores": "Atlantic/Azores",
    "cape verde islands": "Atlantic/Cape_Verde",
    "dublin": "Europe/Dublin",
    "edinburgh": "Europe/London",
    "lisbon": "Europe/Lisbon",
    "london": "Europe/London",
    "casablanca": "Africa/Casablanca",
    "monrovia": "Africa/Monrovia",
    "belgrade": "Europe/Belgrade",
    "bratislava": "Europe/Bratislava",
    "budapest": "Europe/Budapest",
    "ljubljana": "Europe/Ljubljana",
    "prague": "Europe/Prague",
    "sarajevo": "Europe/Sarajevo",
    "skopje": "Europe/Skopje",
    "warsaw": "Europe/Warsaw",
    "zagreb": "Europe/Zagreb",
    "brussels": "Europe/Brussels",
    "copenhagen": "Europe/Copenhagen",
    "madrid": "Europe/Madrid",
    "paris": "Europe/Paris",
    "amsterdam": "Europe/Amsterdam",
    "berlin": "Europe/Berlin",
    "bern": "Europe/Zurich",
    "zurich": "Europe/Zurich",
    "rome": "Europe/Rome",
    "stockholm": "Europe/Stockholm",
    "vienna": "Europe/Vienna",
    "west central africa": "Africa/Algiers",
    "bucharest": "Europe/Bucharest",
    "cairo": "Africa/Cairo",
    "helsinki": "Europe/Helsinki",
    "kyiv": "Europe/Kiev",
    "riga": "Europe/Riga",
    "sofia": "Europe/Sofia",
    "tallinn": "Europe/Tallinn",
    "vilnius": "Europe/Vilnius",
    "athens": "Europe/Athens",
    "istanbul": "Europe/Istanbul",
    "minsk": "Europe/Minsk",
    "jerusalem": "Asia/Jerusalem",
    "harare": "Africa/Harare",
    "pretoria": "Africa/Johannesburg",
    "kaliningrad": "Europe/Kaliningrad",
    "moscow": "Europe/Moscow",
    "st. petersburg": "Europe/Moscow",
    "st petersburg": "Europe/Moscow",
    "volgograd": "Europe/Volgograd",
    "samara": "Europe/Samara",
    "kuwait": "Asia/Kuwait",
    "riyadh": "Asia/Riyadh",
    "nairobi": "Africa/Nairobi",
    "baghdad": "Asia/Baghdad",
    "tehran": "Asia/Tehran",
    "abu dhabi": "Asia/Muscat",
    "muscat": "Asia/Muscat",
    "baku": "Asia/Baku",
    "tbilisi": "Asia/Tbilisi",
    "yerevan": "Asia/Yerevan",
    "kabul": "Asia/Kabul",
    "ekaterinburg": "Asia/Yekaterinburg",
    "islamabad": "Asia/Karachi",
    "karachi": "Asia/Karachi",
    "tashkent": "Asia/Tashkent",
    "chennai": "Asia/Kolkata",
    "kolkata": "Asia/Kolkata",
    "mumbai": "Asia/Kolkata",
    "new delhi": "Asia/Kolkata",
    "kathmandu": "Asia/Kathmandu",
    "astana": "Asia/Dhaka",
    "dhaka": "Asia/Dhaka",
    "sri jayawardenepura": "Asia/Colombo",
    "almaty": "Asia/Almaty",
    "novosibirsk": "Asia/Novosibirsk",
    "rangoon": "Asia/Rangoon",
    "bangkok": "Asia/Bangkok",
    "hanoi": "Asia/Bangkok",
    "jakarta": "Asia/Jakarta",
    "krasnoyarsk": "Asia/Krasnoyarsk",
    "beijing": "Asia/Shanghai",
    "chongqing": "Asia/Chongqing",
    "hong kong": "Asia/Hong_Kong",
    "urumqi": "Asia/Urumqi",
    "kuala lumpur": "Asia/Kuala_Lumpur",
    "singapore": "Asia/Singapore",
    "taipei": "Asia/Taipei",
    "perth": "Australia/Perth",
    "irkutsk": "Asia/Irkutsk",
    "ulaanbaatar": "Asia/Ulaanbaatar",
    "seoul": "Asia/Seoul",
    "osaka": "Asia/Tokyo",
    "sapporo": "Asia/Tokyo",
    "tokyo": "Asia/Tokyo",
    "yakutsk": "Asia/Yakutsk",
    "darwin": "Australia/Darwin",
    "adelaide": "Australia/Adelaide",
    "canberra": "Australia/Melbourne",
    "melbourne": "Australia/Melbourne",
    "sydney": "Australia/Sydney",
    "brisbane": "Australia/Brisbane",
    "hobart": "Australia/Hobart",
    "vladivostok": "Asia/Vladivostok",
    "guam": "Pacific/Guam",
    "port moresby": "Pacific/Port_Moresby",
    "magadan": "Asia/Magadan",
    "srednekolymsk": "Asia/Srednekolymsk",
    "solomon islands": "Pacific/Guadalcanal",
    "new caledonia": "Pacific/Noumea",
    "fiji": "Pacific/Fiji",
    "kamchatka": "Asia/Kamchatka",
    "marshall islands": "Pacific/Majuro",
    "auckland": "Pacific/Auckland",
    "wellington": "Pacific/Auckland",
    "nuku'alofa": "Pacific/Tongatapu",
    "tokelau islands": "Pacific/Fakaofo",
    "chatham islands": "Pacific/Chatham",
    "samoa": "Pacific/Apia",
    "abidjan": "Africa/Abidjan",
    "accra": "Africa/Accra",
    "addis ababa": "Africa/Addis_Ababa",
    "algiers": "Africa/Algiers",
    "asmara": "Africa/Asmara",
    "asmera": "Africa/Asmera",
    "bamako": "Africa/Bamako",
    "bangui": "Africa/Bangui",
    "banjul": "Africa/Banjul",
    "bissau": "Africa/Bissau",
    "blantyre": "Africa/Blantyre",
    "brazzaville": "Africa/Brazzaville",
    "bujumbura": "Africa/Bujumbura",
    "ceuta": "Africa/Ceuta",
    "conakry": "Africa/Conakry",
    "dakar": "Africa/Dakar",
    "dar es salaam": "Africa/Dar_es_Salaam",
    "djibouti": "Africa/Djibouti",
    "douala": "Africa/Douala",
    "el aaiun": "Africa/El_Aaiun",
    "freetown": "Africa/Freetown",
    "gaborone": "Africa/Gaborone",
    "johannesburg": "Africa/Johannesburg",
    "juba": "Africa/Juba",
    "kampala": "Africa/Kampala",
    "khartoum": "Africa/Khartoum",
    "kigali": "Africa/Kigali",
    "kinshasa": "Africa/Kinshasa",
    "lagos": "Africa/Lagos",
    "libreville": "Africa/Libreville",
    "lome": "Africa/Lome",
    "luanda": "Africa/Luanda",
    "lubumbashi": "Africa/Lubumbashi",
    "lusaka": "Africa/Lusaka",
    "malabo": "Africa/Malabo",
    "maputo": "Africa/Maputo",
    "maseru": "Africa/Maseru",
    "mbabane": "Africa/Mbabane",
    "mogadishu": "Africa/Mogadishu",
    "ndjamena": "Africa/Ndjamena",
    "niamey": "Africa/Niamey",
    "nouakchott": "Africa/Nouakchott",
    "ouagadougou": "Africa/Ouagadougou",
    "porto-novo": "Africa/Porto-Novo",
    "sao tome": "Africa/Sao_Tome",
    "timbuktu": "Africa/Timbuktu",
    "tripoli": "Africa/Tripoli",
    "tunis": "Africa/Tunis",
    "windhoek": "Africa/Windhoek",
    "adak": "America/Adak",
    "anchorage": "America/Anchorage",
    "anguilla": "America/Anguilla",
    "antigua": "America/Antigua",
    "araguaina": "America/Araguaina",
    "catamarca": "America/Argentina/Catamarca",
    "comodrivadavia": "America/Argentina/ComodRivadavia",
    "cordoba": "America/Argentina/Cordoba",
    "jujuy": "America/Argentina/Jujuy",
    "la rioja": "America/Argentina/La_Rioja",
    "mendoza": "America/Argentina/Mendoza",
    "rio gallegos": "America/Argentina/Rio_Gallegos",
    "salta": "America/Argentina/Salta",
    "san juan": "America/Argentina/San_Juan",
    "san luis": "America/Argentina/San_Luis",
    "tucuman": "America/Argentina/Tucuman",
    "ushuaia": "America/Argentina/Ushuaia",
    "aruba": "America/Aruba",
    "asuncion": "America/Asuncion",
    "atikokan": "America/Atikokan",
    "atka": "America/Atka",
    "bahia": "America/Bahia",
    "bahia banderas": "America/Bahia_Banderas",
    "barbados": "America/Barbados",
    "belem": "America/Belem",
    "belize": "America/Belize",
    "blanc-sablon": "America/Blanc-Sablon",
    "boa vista": "America/Boa_Vista",
    "boise": "America/Boise",
    "buenos aires": "America/Buenos_Aires",
    "cambridge bay": "America/Cambridge_Bay",
    "campo grande": "America/Campo_Grande",
    "cancun": "America/Cancun",
    "catamarca": "America/Catamarca",
    "cayenne": "America/Cayenne",
    "cayman": "America/Cayman",
    "chicago": "America/Chicago",
    "coral harbour": "America/Coral_Harbour",
    "cordoba": "America/Cordoba",
    "costa rica": "America/Costa_Rica",
    "creston": "America/Creston",
    "cuiaba": "America/Cuiaba",
    "curacao": "America/Curacao",
    "danmarkshavn": "America/Danmarkshavn",
    "dawson": "America/Dawson",
    "dawson creek": "America/Dawson_Creek",
    "denver": "America/Denver",
    "detroit": "America/Detroit",
    "dominica": "America/Dominica",
    "edmonton": "America/Edmonton",
    "eirunepe": "America/Eirunepe",
    "el salvador": "America/El_Salvador",
    "ensenada": "America/Ensenada",
    "fort nelson": "America/Fort_Nelson",
    "fort wayne": "America/Fort_Wayne",
    "fortaleza": "America/Fortaleza",
    "glace bay": "America/Glace_Bay",
    "godthab": "America/Godthab",
    "goose bay": "America/Goose_Bay",
    "grand turk": "America/Grand_Turk",
    "grenada": "America/Grenada",
    "guadeloupe": "America/Guadeloupe",
    "guatemala": "America/Guatemala",
    "guayaquil": "America/Guayaquil",
    "guyana": "America/Guyana",
    "halifax": "America/Halifax",
    "havana": "America/Havana",
    "hermosillo": "America/Hermosillo",
    "knox": "America/Indiana/Knox",
    "marengo": "America/Indiana/Marengo",
    "petersburg": "America/Indiana/Petersburg",
    "tell city": "America/Indiana/Tell_City",
    "vevay": "America/Indiana/Vevay",
    "vincennes": "America/Indiana/Vincennes",
    "winamac": "America/Indiana/Winamac",
    "indianapolis": "America/Indianapolis",
    "inuvik": "America/Inuvik",
    "iqaluit": "America/Iqaluit",
    "jamaica": "America/Jamaica",
    "jujuy": "America/Jujuy",
    "juneau": "America/Juneau",
    "louisville": "America/Kentucky/Louisville",
    "monticello": "America/Kentucky/Monticello",
    "knox in": "America/Knox_IN",
    "kralendijk": "America/Kralendijk",
    "los angeles": "America/Los_Angeles",
    "louisville": "America/Louisville",
    "lower princes": "America/Lower_Princes",
    "maceio": "America/Maceio",
    "managua": "America/Managua",
    "manaus": "America/Manaus",
    "marigot": "America/Marigot",
    "martinique": "America/Martinique",
    "matamoros": "America/Matamoros",
    "mendoza": "America/Mendoza",
    "menominee": "America/Menominee",
    "merida": "America/Merida",
    "metlakatla": "America/Metlakatla",
    "miquelon": "America/Miquelon",
    "moncton": "America/Moncton",
    "montreal": "America/Montreal",
    "montserrat": "America/Montserrat",
    "nassau": "America/Nassau",
    "new york": "America/New_York",
    "nipigon": "America/Nipigon",
    "nome": "America/Nome",
    "noronha": "America/Noronha",
    "beulah": "America/North_Dakota/Beulah",
    "center": "America/North_Dakota/Center",
    "new salem": "America/North_Dakota/New_Salem",
    "ojinaga": "America/Ojinaga",
    "panama": "America/Panama",
    "pangnirtung": "America/Pangnirtung",
    "paramaribo": "America/Paramaribo",
    "phoenix": "America/Phoenix",
    "port-au-prince": "America/Port-au-Prince",
    "port of spain": "America/Port_of_Spain",
    "porto acre": "America/Porto_Acre",
    "porto velho": "America/Porto_Velho",
    "rainy river": "America/Rainy_River",
    "rankin inlet": "America/Rankin_Inlet",
    "recife": "America/Recife",
    "regina": "America/Regina",
    "resolute": "America/Resolute",
    "rio branco": "America/Rio_Branco",
    "rosario": "America/Rosario",
    "santa isabel": "America/Santa_Isabel",
    "santarem": "America/Santarem",
    "santo domingo": "America/Santo_Domingo",
    "sao paulo": "America/Sao_Paulo",
    "scoresbysund": "America/Scoresbysund",
    "shiprock": "America/Shiprock",
    "sitka": "America/Sitka",
    "st barthelemy": "America/St_Barthelemy",
    "st johns": "America/St_Johns",
    "st kitts": "America/St_Kitts",
    "st lucia": "America/St_Lucia",
    "st thomas": "America/St_Thomas",
    "st vincent": "America/St_Vincent",
    "swift current": "America/Swift_Current",
    "tegucigalpa": "America/Tegucigalpa",
    "thule": "America/Thule",
    "thunder bay": "America/Thunder_Bay",
    "toronto": "America/Toronto",
    "tortola": "America/Tortola",
    "vancouver": "America/Vancouver",
    "virgin": "America/Virgin",
    "whitehorse": "America/Whitehorse",
    "winnipeg": "America/Winnipeg",
    "yakutat": "America/Yakutat",
    "yellowknife": "America/Yellowknife",
    "casey": "Antarctica/Casey",
    "davis": "Antarctica/Davis",
    "dumontdurville": "Antarctica/DumontDUrville",
    "macquarie": "Antarctica/Macquarie",
    "mawson": "Antarctica/Mawson",
    "mcmurdo": "Antarctica/McMurdo",
    "palmer": "Antarctica/Palmer",
    "rothera": "Antarctica/Rothera",
    "south pole": "Antarctica/South_Pole",
    "syowa": "Antarctica/Syowa",
    "troll": "Antarctica/Troll",
    "vostok": "Antarctica/Vostok",
    "longyearbyen": "Arctic/Longyearbyen",
    "aden": "Asia/Aden",
    "amman": "Asia/Amman",
    "anadyr": "Asia/Anadyr",
    "aqtau": "Asia/Aqtau",
    "aqtobe": "Asia/Aqtobe",
    "ashgabat": "Asia/Ashgabat",
    "ashkhabad": "Asia/Ashkhabad",
    "bahrain": "Asia/Bahrain",
    "barnaul": "Asia/Barnaul",
    "beirut": "Asia/Beirut",
    "bishkek": "Asia/Bishkek",
    "brunei": "Asia/Brunei",
    "calcutta": "Asia/Calcutta",
    "chita": "Asia/Chita",
    "choibalsan": "Asia/Choibalsan",
    "chungking": "Asia/Chungking",
    "colombo": "Asia/Colombo",
    "dacca": "Asia/Dacca",
    "damascus": "Asia/Damascus",
    "dili": "Asia/Dili",
    "dubai": "Asia/Dubai",
    "dushanbe": "Asia/Dushanbe",
    "gaza": "Asia/Gaza",
    "harbin": "Asia/Harbin",
    "hebron": "Asia/Hebron",
    "ho chi minh": "Asia/Ho_Chi_Minh",
    "hovd": "Asia/Hovd",
    "istanbul": "Asia/Istanbul",
    "jayapura": "Asia/Jayapura",
    "kashgar": "Asia/Kashgar",
    "katmandu": "Asia/Katmandu",
    "khandyga": "Asia/Khandyga",
    "kuching": "Asia/Kuching",
    "macao": "Asia/Macao",
    "macau": "Asia/Macau",
    "makassar": "Asia/Makassar",
    "manila": "Asia/Manila",
    "nicosia": "Asia/Nicosia",
    "novokuznetsk": "Asia/Novokuznetsk",
    "omsk": "Asia/Omsk",
    "oral": "Asia/Oral",
    "phnom penh": "Asia/Phnom_Penh",
    "pontianak": "Asia/Pontianak",
    "pyongyang": "Asia/Pyongyang",
    "qatar": "Asia/Qatar",
    "qyzylorda": "Asia/Qyzylorda",
    "saigon": "Asia/Saigon",
    "sakhalin": "Asia/Sakhalin",
    "samarkand": "Asia/Samarkand",
    "shanghai": "Asia/Shanghai",
    "tel aviv": "Asia/Tel_Aviv",
    "thimbu": "Asia/Thimbu",
    "thimphu": "Asia/Thimphu",
    "tomsk": "Asia/Tomsk",
    "ujung pandang": "Asia/Ujung_Pandang",
    "ulan bator": "Asia/Ulan_Bator",
    "ust-nera": "Asia/Ust-Nera",
    "vientiane": "Asia/Vientiane",
    "yekaterinburg": "Asia/Yekaterinburg",
    "bermuda": "Atlantic/Bermuda",
    "canary": "Atlantic/Canary",
    "cape verde": "Atlantic/Cape_Verde",
    "faeroe": "Atlantic/Faeroe",
    "faroe": "Atlantic/Faroe",
    "jan mayen": "Atlantic/Jan_Mayen",
    "madeira": "Atlantic/Madeira",
    "reykjavik": "Atlantic/Reykjavik",
    "south georgia": "Atlantic/South_Georgia",
    "st helena": "Atlantic/St_Helena",
    "stanley": "Atlantic/Stanley",
    "act": "Australia/ACT",
    "broken hill": "Australia/Broken_Hill",
    "canberra": "Australia/Canberra",
    "currie": "Australia/Currie",
    "eucla": "Australia/Eucla",
    "lhi": "Australia/LHI",
    "lindeman": "Australia/Lindeman",
    "lord howe": "Australia/Lord_Howe",
    "nsw": "Australia/NSW",
    "north": "Australia/North",
    "queensland": "Australia/Queensland",
    "south": "Australia/South",
    "tasmania": "Australia/Tasmania",
    "victoria": "Australia/Victoria",
    "west": "Australia/West",
    "yancowinna": "Australia/Yancowinna",
    "acre": "Brazil/Acre",
    "denoronha": "Brazil/DeNoronha",
    "east": "Brazil/East",
    "west": "Brazil/West",
    "atlantic": "Canada/Atlantic",
    "central": "Canada/Central",
    "east-saskatchewan": "Canada/East-Saskatchewan",
    "eastern": "Canada/Eastern",
    "mountain": "Canada/Mountain",
    "newfoundland": "Canada/Newfoundland",
    "pacific": "Canada/Pacific",
    "saskatchewan": "Canada/Saskatchewan",
    "yukon": "Canada/Yukon",
    "continental": "Chile/Continental",
    "easterisland": "Chile/EasterIsland",
    "andorra": "Europe/Andorra",
    "astrakhan": "Europe/Astrakhan",
    "belfast": "Europe/Belfast",
    "busingen": "Europe/Busingen",
    "chisinau": "Europe/Chisinau",
    "gibraltar": "Europe/Gibraltar",
    "guernsey": "Europe/Guernsey",
    "isle of man": "Europe/Isle_of_Man",
    "jersey": "Europe/Jersey",
    "kiev": "Europe/Kiev",
    "kirov": "Europe/Kirov",
    "luxembourg": "Europe/Luxembourg",
    "malta": "Europe/Malta",
    "mariehamn": "Europe/Mariehamn",
    "monaco": "Europe/Monaco",
    "nicosia": "Europe/Nicosia",
    "oslo": "Europe/Oslo",
    "podgorica": "Europe/Podgorica",
    "san marino": "Europe/San_Marino",
    "simferopol": "Europe/Simferopol",
    "tirane": "Europe/Tirane",
    "tiraspol": "Europe/Tiraspol",
    "ulyanovsk": "Europe/Ulyanovsk",
    "uzhgorod": "Europe/Uzhgorod",
    "vaduz": "Europe/Vaduz",
    "vatican": "Europe/Vatican",
    "zaporozhye": "Europe/Zaporozhye",
    "antananarivo": "Indian/Antananarivo",
    "chagos": "Indian/Chagos",
    "christmas": "Indian/Christmas",
    "cocos": "Indian/Cocos",
    "comoro": "Indian/Comoro",
    "kerguelen": "Indian/Kerguelen",
    "mahe": "Indian/Mahe",
    "maldives": "Indian/Maldives",
    "mauritius": "Indian/Mauritius",
    "mayotte": "Indian/Mayotte",
    "reunion": "Indian/Reunion",
    "bajanorte": "Mexico/BajaNorte",
    "bajasur": "Mexico/BajaSur",
    "apia": "Pacific/Apia",
    "bougainville": "Pacific/Bougainville",
    "chatham": "Pacific/Chatham",
    "chuuk": "Pacific/Chuuk",
    "easter": "Pacific/Easter",
    "efate": "Pacific/Efate",
    "enderbury": "Pacific/Enderbury",
    "fakaofo": "Pacific/Fakaofo",
    "funafuti": "Pacific/Funafuti",
    "galapagos": "Pacific/Galapagos",
    "gambier": "Pacific/Gambier",
    "guadalcanal": "Pacific/Guadalcanal",
    "honolulu": "Pacific/Honolulu",
    "johnston": "Pacific/Johnston",
    "kiritimati": "Pacific/Kiritimati",
    "kosrae": "Pacific/Kosrae",
    "kwajalein": "Pacific/Kwajalein",
    "majuro": "Pacific/Majuro",
    "marquesas": "Pacific/Marquesas",
    "midway": "Pacific/Midway",
    "nauru": "Pacific/Nauru",
    "niue": "Pacific/Niue",
    "norfolk": "Pacific/Norfolk",
    "noumea": "Pacific/Noumea",
    "pago pago": "Pacific/Pago_Pago",
    "palau": "Pacific/Palau",
    "pitcairn": "Pacific/Pitcairn",
    "pohnpei": "Pacific/Pohnpei",
    "ponape": "Pacific/Ponape",
    "rarotonga": "Pacific/Rarotonga",
    "saipan": "Pacific/Saipan",
    "samoa": "Pacific/Samoa",
    "tahiti": "Pacific/Tahiti",
    "tarawa": "Pacific/Tarawa",
    "tongatapu": "Pacific/Tongatapu",
    "truk": "Pacific/Truk",
    "wake": "Pacific/Wake",
    "wallis": "Pacific/Wallis",
    "yap": "Pacific/Yap",
    "india": "Asia/Kolkata",
    "-01": "Ext/GMT-1",
    "-02": "Ext/GMT-2",
    "-03": "Ext/GMT-3",
    "-04": "Ext/GMT-4",
    "-05": "Ext/GMT-5",
    "-06": "Ext/GMT-6",
    "-07": "Ext/GMT-7",
    "-08": "Ext/GMT-8",
    "-09": "Ext/GMT-9",
    "-0930": "Pacific/Marquesas",
    "-10": "Ext/GMT-10",
    "-11": "Ext/GMT-11",
    "+00": "UTC",
    "+0020": "Africa/Accra",
    "+01": "Ext/GMT+1",
    "+02": "Ext/GMT+2",
    "+03": "Ext/GMT+3",
    "+0330": "Asia/Tehran",
    "+04": "Ext/GMT+4",
    "+0430": "Asia/Tehran",
    "+05": "Ext/GMT+5",
    "+0530": "Asia/Colombo",
    "+0545": "Asia/Kathmandu",
    "+06": "Ext/GMT+6",
    "+0630": "Asia/Kolkata",
    "+07": "Ext/GMT+7",
    "+08": "Ext/GMT+8",
    "+0845": "Australia/Eucla",
    "+09": "Ext/GMT+9",
    "+0945": "Australia/Eucla",
    "+10": "Ext/GMT+10",
    "+1030": "Australia/Lord_Howe",
    "+11": "Ext/GMT+11",
    "+12": "Ext/GMT+12",
    "+1245": "Pacific/Chatham",
    "+13": "Ext/GMT+13",
    "+1345": "Pacific/Chatham",
    "+14": "Pacific/Kiritimati",
    "acdt": "Australia/Adelaide",
    "acst": "Australia/Adelaide",
    "act": "Australia/Darwin",
    "acwdt": "Australia/Perth",
    "acwst": "Australia/Perth",
    "adt": "America/Barbados",
    "aedt": "Australia/Sydney",
    "aest": "Australia/Sydney",
    "aet": "Australia/Sydney",
    "aft": "Asia/Kabul",
    "akdt": "America/Juneau",
    "akst": "America/Juneau",
    "almt": "Asia/Almaty",
    "amst": "America/Cuiaba",
    "amt": "America/Cuiaba",
    "anast": "Asia/Anadyr",
    "anat": "Asia/Anadyr",
    "apt": "America/Puerto_Rico",
    "aqtt": "Asia/Aqtobe",
    "art": "America/Argentina/Buenos_Aires",
    "ast": "America/Puerto_Rico",
    "awdt": "Australia/Perth",
    "awst": "Australia/Perth",
    "azost": "Atlantic/Azores",
    "azot": "Atlantic/Azores",
    "azst": "Asia/Baku",
    "azt": "Asia/Baku",
    "bdt": "Asia/Dhaka",
    "biot": "Indian/Chagos",
    "bit": "Asia/Makassar",
    "bot": "America/La_Paz",
    "brst": "America/Sao_Paulo",
    "brt": "America/Sao_Paulo",
    "bst": "Europe/London",
    "btt": "Asia/Thimphu",
    "cat": "Africa/Harare",
    "cct": "Indian/Cocos",
    "cddt": "America/Cayenne",
    "cdt": "America/Cayenne",
    "cedt": "Europe/Helsinki",
    "cest": "Europe/Helsinki",
    "cet": "Europe/Madrid",
    "chadt": "Pacific/Chatham",
    "chast": "Pacific/Chatham",
    "chst": "Pacific/Guam",
    "cist": "Pacific/Pitcairn",
    "ckt": "Pacific/Rarotonga",
    "clst": "America/Santiago",
    "clt": "America/Santiago",
    "cost": "America/Bogota",
    "cot": "America/Bogota",
    "cst": "America/Chicago",
    "ct": "America/Chicago",
    "cvt": "Atlantic/Cape_Verde",
    "cwt": "America/Chicago",
    "cxt": "Indian/Christmas",
    "davt": "Antarctica/Davis",
    "ddut": "Antarctica/DumontDUrville",
    "dft": "Europe/Oslo",
    "east": "Pacific/Easter",
    "eat": "Africa/Djibouti",
    "ect": "Europe/Guayaquil",
    "edt": "America/New_York",
    "eest": "Europe/Istanbul",
    "eet": "Europe/Istanbul",
    "egst": "Europe/London",
    "egt": "Europe/London",
    "eit": "Asia/Jayapura",
    "est": "America/New_York",
    "et": "America/New_York",
    "fet": "Europe/Minsk",
    "fjt": "Pacific/Fiji",
    "fkst": "Atlantic/Stanley",
    "fkt": "Atlantic/Stanley",
    "fnt": "America/Noronha",
    "galt": "Pacific/Galapagos",
    "gamt": "Pacific/Gambier",
    "gdt": "Pacific/Guam",
    "get": "Asia/Tbilisi",
    "gft": "America/Cayenne",
    "gilt": "Pacific/Tarawa",
    "git": "Pacific/Gambier",
    "gmt": "GMT",
    "gst": "Asia/Dubai",
    "gyt": "America/Guyana",
    "hadt": "Pacific/Honolulu",
    "haec": "Europe/Berlin",
    "hast": "Pacific/Honolulu",
    "hdt": "America/Adak",
    "hkst": "Asia/Hong_Kong",
    "hkt": "Asia/Hong_Kong",
    "hmt": "Asia/Kolkata",
    "hovt": "Asia/Hovd",
    "hst": "Pacific/Honolulu",
    "ict": "Asia/Bangkok",
    "idt": "Asia/Jerusalem",
    "iot": "Indian/Chagos",
    "irdt": "Asia/Tehran",
    "irkt": "Asia/Irkutsk",
    "irst": "Asia/Tehran",
    "ist": "Asia/Kolkata",
    "jdt": "Asia/Tokyo",
    "jst": "Asia/Tokyo",
    "kdt": "Asia/Seoul",
    "kgt": "Asia/Bishkek",
    "kost": "Pacific/Kosrae",
    "krat": "Asia/Krasnoyarsk",
    "kst": "Asia/Seoul",
    "kuyt": "Europe/Samara",
    "lhst": "Australia/Lord_Howe",
    "lint": "Pacific/Kiritimati",
    "lkt": "Asia/Colombo",
    "magt": "Pacific/Magadan",
    "mart": "Pacific/Marquesas",
    "mawt": "Antarctica/Mawson",
    "mdt": "America/Denver",
    "mht": "Pacific/Majuro",
    "mist": "Antarctica/Macquarie",
    "msk": "Europe/Moscow",
    "mst": "America/Denver",
    "mt": "America/Denver",
    "mut": "Indian/Mauritius",
    "mvt": "Indian/Maldives",
    "myt": "Asia/Kuala_Lumpur",
    "nct": "Pacific/Noumea",
    "ndt": "America/St_Johns",
    "nft": "Pacific/Norfolk",
    "novt": "Asia/Novosibirsk",
    "npt": "Asia/Katmandu",
    "nst": "America/St_Johns",
    "nut": "Pacific/Niue",
    "nzdt": "Pacific/Auckland",
    "nzst": "Pacific/Auckland",
    "omst": "Asia/Omsk",
    "omt": "Asia/Omsk",
    "pdt": "America/Los_Angeles",
    "pet": "America/Lima",
    "pett": "Asia/Kamchatka",
    "pgt": "Pacific/Port_Moresby",
    "phot": "Pacific/Enderbury",
    "pht": "Asia/Manila",
    "pkst": "Asia/Karachi",
    "pkt": "Asia/Karachi",
    "pmdt": "America/Miquelon",
    "pmst": "America/Miquelon",
    "pont": "Pacific/Ponape",
    "pst": "America/Los_Angeles",
    "pt": "America/Los_Angeles",
    "pwt": "Pacific/Palau",
    "pyst": "America/Asuncion",
    "pyt": "America/Asuncion",
    "ret": "Indian/Reunion",
    "rott": "Antarctica/Rothera",
    "sakt": "Asia/Krasnoyarsk",
    "samt": "Europe/Samara",
    "sast": "Africa/Johannesburg",
    "sbt": "Pacific/Guadalcanal",
    "sct": "Indian/Mahe",
    "sgt": "Asia/Singapore",
    "slst": "Africa/Freetown",
    "sret": "Asia/Srednekolymsk",
    "srt": "America/Paramaribo",
    "sst": "Pacific/Samoa",
    "syot": "Antarctica/Syowa",
    "taht": "Pacific/Tahiti",
    "tft": "Indian/Kerguelen",
    "tha": "Asia/Bangkok",
    "tjt": "Asia/Dushanbe",
    "tkt": "Pacific/Fakaofo",
    "tlt": "Asia/Dili",
    "tmt": "Asia/Ashkhabad",
    "tot": "Pacific/Tongatapu",
    "tvt": "Pacific/Funafuti",
    "ulast": "Asia/Ulaanbaatar",
    "ulat": "Asia/Ulaanbaatar",
    "utc": "Europe/London",
    "uyst": "America/Montevideo",
    "uyt": "America/Montevideo",
    "uzt": "Asia/Tashkent",
    "vet": "America/Caracas",
    "vlast": "Asia/Vladivostok",
    "vlat": "Asia/Vladivostok",
    "vut": "Pacific/Efate",
    "wakt": "Pacific/Wake",
    "wast": "Africa/Windhoek",
    "wat": "Africa/Johannesburg",
    "west": "Europe/Lisbon",
    "wet": "Europe/Lisbon",
    "wft": "Pacific/Wallis",
    "wgst": "America/Sao_Paulo",
    "wgt": "America/Sao_Paulo",
    "wib": "Asia/Jakarta",
    "wit": "Asia/Jayapura",
    "wita": "Asia/Makassar",
    "wst": "Pacific/Apia",
    "yakt": "Asia/Yakutsk",
    "yekst": "Asia/Yekaterinburg",
    "yekt": "Asia/Yekaterinburg",
    "z": "UTC",
}
